# Generated by Django 5.2.4 on 2025-09-22 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tguser',
            name='context',
            field=models.JSONField(blank=True, null=True, verbose_name='Контекст диалога'),
        ),
        migrations.AddField(
            model_name='tguser',
            name='state',
            field=models.CharField(choices=[('start', 'Старт'), ('wating_master_first_name', 'Ожидание имени мастера'), ('wating_master_last_name', 'Ожидание фамилии мастера'), ('wating_specialization', 'Ожидание специализации'), ('wating_experience', 'Ожидание опыта мастера'), ('wating_salon', 'Ожидание номера салона')], default='start', max_length=50, verbose_name='Состояние диалога'),
        ),
    ]
