# Generated by Django 5.2.6 on 2025-10-13 17:46

import django_fsm
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_tguser_context_tguser_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tguser',
            name='state',
            field=django_fsm.FSMField(choices=[('start', 'Старт'), ('wating_master_first_name', 'Ожидание имени мастера'), ('wating_master_last_name', 'Ожидание фамилии мастера'), ('wating_specialization', 'Ожидание специализации'), ('wating_experience', 'Ожидание опыта мастера'), ('wating_salon', 'Ожидание номера салона')], default='start', max_length=50, protected=True, verbose_name='Состояние диалога'),
        ),
    ]
